"""Code analysis skills for the Agentic Evaluator."""

from .code_analyzer import (
    check_build_scripts,
    check_design_patterns,
    check_env_config,
    check_error_handling,
    check_extensibility,
    check_inline_documentation,
    check_lint_config,
    check_logging_config,
    check_module_interfaces,
    check_naming_consistency,
    check_refactoring_safety,
    check_schema_validation,
    check_type_annotations,
)
from .file_scanner import (
    analyze_directory_structure,
    check_devcontainer,
    check_file_exists,
    list_files_by_extension,
    read_file_content,
    scan_repository,
)
from .git_analyzer import (
    analyze_git_history,
    check_adr_records,
    check_ci_config,
    check_dependency_transparency,
    check_gitignore,
    count_test_files,
)
from .lang_analyzer import (
    check_go_module,
    check_java_build,
    check_sql_migrations,
    check_vue_components,
)

__all__ = [
    "scan_repository",
    "check_file_exists",
    "read_file_content",
    "list_files_by_extension",
    "analyze_directory_structure",
    "check_devcontainer",
    "check_type_annotations",
    "check_naming_consistency",
    "check_inline_documentation",
    "check_schema_validation",
    "check_module_interfaces",
    "check_env_config",
    "check_lint_config",
    "check_build_scripts",
    "check_error_handling",
    "check_logging_config",
    "check_design_patterns",
    "check_extensibility",
    "check_refactoring_safety",
    "analyze_git_history",
    "check_ci_config",
    "check_gitignore",
    "check_adr_records",
    "count_test_files",
    "check_dependency_transparency",
    "check_go_module",
    "check_java_build",
    "check_vue_components",
    "check_sql_migrations",
]
